version: "3.9"

services:

  server:
    depends_on:
      - postgres
    build: ./server
    environment:
      - "JVM_XMS=2G"
      - "JVM_XMX=4G"
    volumes:
      - "./server-data:/server"
    ports:
      - "25565:25565"

  postgres:
    image: postgres:13.3-alpine
    environment:
      - "POSTGRES_PASSWORD=dev"
    volumes:
      - "./postgres_data:/var/lib/postgresql/data"
